databases:
  - name: ServidorIsma
    plan: free
    databaseName: dbtesis
    user: isma

services:
  - type: web
    plan: free
    name: Tesis
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Tesis.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ServidorIsma
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: tesis-7eay.onrender.com



# set DATABASE_URL=postgresql://isma:gGzmuPP2aCY469LweKKj5GSv5G5VQFYM@dpg-cqlpned6l47c73fj9djg-a.oregon-postgres.render.com/dbcine_2a9q